name: dan-sam
on:
  push:
    branches: ["main"]
jobs:
  build_image:
    name: build docker
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: loginaws
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{secrets.awsaccesskey}}
          aws-secret-access-key: ${{secrets.awssecretkey}}
          aws-region: ${{vars.awsregion}}
      - name: loginecr
        uses: aws-actions/amazon-ecr-login@v2
        id: loginecr
      - name: build & push
        env:
          ecrregistry: ${{steps.loginecr.outputs.registry}}
        run:
          echo $ecrregistry
